#!/bin/sh
mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev
VEHICLE_ID=
export VEHICLE_ID
echo 'Bringing up eth0...'
ip link set dev eth0 up
echo 'Network interface is up. Launching application.'
./build/start_car 4
exec /bin/sh
