var annotated_dup =
[
    [ "Address", "class_address.html", "class_address" ],
    [ "Buffer", "class_buffer.html", "class_buffer" ],
    [ "Communicator", "class_communicator.html", "class_communicator" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "ComponentHolder", "struct_component_holder.html", "struct_component_holder" ],
    [ "ComponentPorts", "class_component_ports.html", "class_component_ports" ],
    [ "ConcreteHolder", "struct_concrete_holder.html", "struct_concrete_holder" ],
    [ "Concurrent_Observed", "class_concurrent___observed.html", "class_concurrent___observed" ],
    [ "Concurrent_Observer", "class_concurrent___observer.html", "class_concurrent___observer" ],
    [ "Conditional_Data_Observer", "class_conditional___data___observer.html", "class_conditional___data___observer" ],
    [ "Conditional_Data_Observer< T, void >", "class_conditional___data___observer_3_01_t_00_01void_01_4.html", "class_conditional___data___observer_3_01_t_00_01void_01_4" ],
    [ "Conditionally_Data_Observed", "class_conditionally___data___observed.html", "class_conditionally___data___observed" ],
    [ "DataGenerator", "class_data_generator.html", "class_data_generator" ],
    [ "Ethernet", "class_ethernet.html", "class_ethernet" ],
    [ "Gateway", "class_gateway.html", "class_gateway" ],
    [ "LocalSmartData", "class_local_smart_data.html", "class_local_smart_data" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "Message", "class_message.html", "class_message" ],
    [ "NIC", "class_n_i_c.html", "class_n_i_c" ],
    [ "Protocol", "class_protocol.html", "class_protocol" ],
    [ "RawSocketEngine", "class_raw_socket_engine.html", "class_raw_socket_engine" ],
    [ "Semaphore", "class_semaphore.html", "class_semaphore" ],
    [ "ShmEngine", "class_shm_engine.html", "class_shm_engine" ],
    [ "SmartData", "class_smart_data.html", "class_smart_data" ],
    [ "Statistics", "class_statistics.html", "class_statistics" ],
    [ "Traits", "struct_traits.html", null ],
    [ "Traits< Protocol< NIC, NIC2 > >", "struct_traits_3_01_protocol_3_01_n_i_c_00_01_n_i_c2_01_4_01_4.html", "struct_traits_3_01_protocol_3_01_n_i_c_00_01_n_i_c2_01_4_01_4" ],
    [ "Transducer", "class_transducer.html", "class_transducer" ]
];